### ISSUE TITLE
TS2307: CSS Modules

### ISSUE THREAD

**Issue by alekseykurylev** [asynchroza/vite-npm-package-template#1]
Hi! I can't get rid of the error when using CSS Modules. Tell me how to fix it.

![image](https://github.com/asynchroza/vite-npm-package-template/assets/8526127/d8f2cad5-07f6-4b6a-ab0a-9bef0953f424)

**Comment by asynchroza** [comment]
One quick workaround would be this:

```typescript
import React from 'react';
// eslint-disable-next-line
// @ts-ignore
import styles from './Button.module.css';


function App() {
  return <h1 className={(styles as any).hello}>HELLO WORLD</h1>
}

export default App;
```

Otherwise, a real type safe approach would be:
```typescript
import React from 'react';
import * as css from './Button.module.css';


function App() {
  return <h1 className={css.hello}>HELLO WORLD</h1>
}

export default App;

```

`Button.module.css`:
```css
.hello {
    color: red;
}
```

And in the same directory you need a file -> `Button.module.css.d.ts`:
Declare your classNames:

```typescript
export const hello: string;
```
